/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connect.DatabaseHelper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NgonNgu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbNhoMK = new javax.swing.JCheckBox();
        lbMK = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbQuenMK = new javax.swing.JLabel();
        lbten = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTenDN = new javax.swing.JTextField();
        lbTieuDe = new javax.swing.JLabel();
        btDN = new javax.swing.JButton();
        btDK = new javax.swing.JButton();
        tfMK = new javax.swing.JPasswordField();
        rbEng = new javax.swing.JRadioButton();
        rbViet = new javax.swing.JRadioButton();
        lbNN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setLocation(new java.awt.Point(350, 150));

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbNhoMK.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        cbNhoMK.setText("Nhớ mât khẩu");
        jPanel1.add(cbNhoMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 192, -1, -1));

        lbMK.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        lbMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_lock_30px_1.png"))); // NOI18N
        lbMK.setText("Mật Khẩu:");
        jPanel1.add(lbMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 128, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 107, 367, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 164, 367, 10));

        lbQuenMK.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        lbQuenMK.setText("Quên mật khẩu ?");
        jPanel1.add(lbQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 196, -1, -1));

        lbten.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        lbten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_30px_2.png"))); // NOI18N
        lbten.setText("Tên ĐN:");
        jPanel1.add(lbten, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 69, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SeekPng.com_green-light-png_928267 (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 19, -1, -1));

        tfTenDN.setBackground(new java.awt.Color(236, 240, 241));
        tfTenDN.setBorder(null);
        jPanel1.add(tfTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 71, 259, 30));

        lbTieuDe.setFont(new java.awt.Font("UTM Loko", 0, 24)); // NOI18N
        lbTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieuDe.setText("Đăng Nhập ");
        jPanel1.add(lbTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, 362, -1));

        btDN.setBackground(new java.awt.Color(0, 0, 0));
        btDN.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btDN.setForeground(new java.awt.Color(255, 255, 255));
        btDN.setText("Đăng nhập");
        btDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDNActionPerformed(evt);
            }
        });
        jPanel1.add(btDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 253, 367, 41));

        btDK.setBackground(new java.awt.Color(46, 204, 113));
        btDK.setFont(new java.awt.Font("UTM Avo", 1, 12)); // NOI18N
        btDK.setForeground(new java.awt.Color(255, 255, 255));
        btDK.setText("Đăng ki tài khoản");
        btDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDKActionPerformed(evt);
            }
        });
        jPanel1.add(btDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 312, 160, -1));

        tfMK.setBackground(new java.awt.Color(236, 240, 241));
        tfMK.setBorder(null);
        jPanel1.add(tfMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 128, 259, 30));

        NgonNgu.add(rbEng);
        rbEng.setFont(new java.awt.Font("UTM Avo", 1, 12)); // NOI18N
        rbEng.setText("ENG");
        rbEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEngActionPerformed(evt);
            }
        });
        jPanel1.add(rbEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 382, -1, -1));

        NgonNgu.add(rbViet);
        rbViet.setFont(new java.awt.Font("UTM Avo", 1, 12)); // NOI18N
        rbViet.setSelected(true);
        rbViet.setText("VIE");
        rbViet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVietActionPerformed(evt);
            }
        });
        jPanel1.add(rbViet, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 382, -1, -1));

        lbNN.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        lbNN.setText("Ngôn Ngữ");
        jPanel1.add(lbNN, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 387, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDKActionPerformed
        // TODO add your handling code here:
        new DangKi().show();
        this.hide();
    }//GEN-LAST:event_btDKActionPerformed

    private void btDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDNActionPerformed
        // TODO add your handling code here:
        if (tfTenDN.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập tên đăng nhập");
            return;
        }
        if (tfMK.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập mật khẩu");
            return;
        }
        try {
            Connection conn =DatabaseHelper.getConnection();
            String sql = "SELECT * FROM NguoiDung "
                    + "WHERE tenDN=? AND matKhau=? ";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1,tfTenDN.getText());
            ps.setString(2,tfMK.getText());
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                JOptionPane.showMessageDialog(this,"Đăng nhập thành công");
                new TrangChu().show();
                this.hide();
                
            } else {
                JOptionPane.showMessageDialog(null, "Tên tài khoản hoặc mật khẩu không chính xác");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi : " + e.getMessage());
            Logger.getLogger(Connection.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btDNActionPerformed

    private void rbVietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVietActionPerformed
        // TODO add your handling code here:
        lbTieuDe.setText("Đăng Nhập");
        lbten.setText("Tên ĐN:");
        lbMK.setText("Mật Khẩu:");
        btDN.setText("Đăng nhập");
        btDK.setText("Đăng kí tài khoản");
        cbNhoMK.setText("Nhớ mật khẩu");
        lbQuenMK.setText("Quên mật khẩu ?");
        lbNN.setText("Ngôn Ngữ");
    }//GEN-LAST:event_rbVietActionPerformed

    private void rbEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEngActionPerformed
        // TODO add your handling code here:
        lbTieuDe.setText("Log in");
        lbten.setText("User Name:");
        lbMK.setText("Password:");
        btDN.setText("Login");
        btDK.setText("Sign Up");
        cbNhoMK.setText("Remember");
        lbQuenMK.setText("Forgot password ?");
        lbNN.setText("Language");
    }//GEN-LAST:event_rbEngActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup NgonNgu;
    private javax.swing.JButton btDK;
    private javax.swing.JButton btDN;
    private javax.swing.JCheckBox cbNhoMK;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbMK;
    private javax.swing.JLabel lbNN;
    private javax.swing.JLabel lbQuenMK;
    private javax.swing.JLabel lbTieuDe;
    private javax.swing.JLabel lbten;
    private javax.swing.JRadioButton rbEng;
    private javax.swing.JRadioButton rbViet;
    private javax.swing.JPasswordField tfMK;
    private javax.swing.JTextField tfTenDN;
    // End of variables declaration//GEN-END:variables
}
